services:
  workshop:
    build: .
    container_name: meta-repo-workshop
    ports:
      - "8080:80"
    volumes:
      # Mount for live editing during development
      - ./slides:/usr/share/nginx/html/slides:ro
      - ./workshop:/usr/share/nginx/html/workshop:ro
      - ./resources:/usr/share/nginx/html/resources:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped

  # Optional: Development container with all tools
  dev:
    image: node:18-alpine
    container_name: workshop-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - workshop-repos:/repos
    command: /bin/sh -c "apk add --no-cache git python3 py3-pip py3-yaml bash make curl && npm install -g meta && tail -f /dev/null"
    environment:
      - TERM=xterm-256color

volumes:
  workshop-repos:
    driver: local
